seata:
  #是否开启spring-boot自动装配
  enabled: true
  application-id: seata-server
  #是否开启数据源自动代理
  enable-auto-data-source-proxy: true
  #事务组名称
  #指定事务分组至集群映射关系（等号右侧的集群名需要与Seata-server注册到Nacos的cluster保持一致）
  tx-service-group: cd-tx-group

  config:
    type: nacos
    nacos:
      server-addr: 106.52.253.159:10010
      group: SEATA_GROUP
      namespace: koinpay

  registry:
    type: nacos
    nacos:
      application: seata-server
      cluster: cd-seata-group
      server-addr: 106.52.253.159:10010
      group: SEATA_GROUP
      namespace: koinpay

  service:
    disable-global-transaction: false
    vgroup-mapping:
      cd-tx-group: cd-seata-group

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: log.log
  level:
    root: info
